### ISSUE TITLE
one-way-input, cursor jumps to end

### ISSUE THREAD

**Issue by Samsinite** [DockYard/ember-one-way-controls#122] opened 2016-09-20 18:23 UTC
For starters, I'm on an app running Ember 1.13.13, and ember-one-way-controls 1.1.1. Typing at the beginning of the input, the cursor jumps all the way to the end of the input.

Application Usage:

``` hbs
{{one-way-input person.firstName
  update=(action (mut person.firstName))}}
```

**Comment by martndemus** [comment] 2016-09-26 16:24
Can't reproduce this. Can you make an ember-twiddle that reproduces the error?

**Comment by Samsinite** [comment] 2016-09-26 16:29
Sure, how do you install an addon for ember-twiddle?

**Comment by martndemus** [comment] 2016-09-26 16:30
```
  "addons": {
    "ember-one-way-controls": "1.1.1"
  }
```

In `twiddle.json`

**Comment by Samsinite** [comment] 2016-09-26 16:39
Here you go https://ember-twiddle.com/18bd0697c36d8cf5eae5d492a25775ab

**Comment by Samsinite** [comment] 2016-09-26 16:40
0.9.2 works as expected btw :)

**Comment by Samsinite** [comment] 2016-09-26 18:45
Oh btw, tried it on ember 2.8 on twiddle and the same error happens :/.

**Comment by tsteuwer** [comment] 2016-11-13 18:20
@Samsinite , I just edited your twiddle and removed your template/testing dependencies and updated ember to 2.8.2 and it works?

**Comment by tomwayson** [comment] 2017-02-05 17:57
I can confirm that when visiting the twiddle in Chrome I saw the error, but then updating the Ember.js dep to 2.8.2 like so:

![image](https://cloud.githubusercontent.com/assets/662944/22628442/f2183f90-eb88-11e6-967b-7a15d21ba523.png)

Caused the error to go away.

@Samsinite if you'r still seeing the error on ember  2.8, may I ask what browser you're using? We have an app that's is showing similar problems (not using ember-one-way-controls, just native `input` and `textarea` controls and binding actions to their `input`, but we're _only_ seeing the issue for IE10 users.

**Comment by martndemus** [comment] 2018-01-11 09:55
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.

**Closed by martndemus** 2018-01-11 09:55 UTC

**Comment by Samsinite** [comment] 2018-01-11 19:13
Makes sense. We stopped using this add-on as well since it isn't needed
anymore. Thanks for the hard work put into it and the feedback.
