### ISSUE TITLE
Input element required attribute bug in Firefox

### ISSUE THREAD

**Issue by Ctannerweb** [DockYard/ember-one-way-controls#158] opened 2017-05-12 15:53 UTC
Example of `<input>` element when you first land on the page and Firefox jumping the gun on validation.
![screen shot 2017-05-12 at 11 46 48 am](https://cloud.githubusercontent.com/assets/8336499/26005953/bbac835a-3708-11e7-8d8e-1958411847d9.png)

Looks like the page is being fed `required=""` on `<input>` fields and firefox doesn't know how to handle that. If Firefox is fed `required` only the issue should be resolved. `required="true"` will work as well but `required` falls in line with html5 spec.

As a side note, `<select>` fields behave correctly with validation and will only apply an outline after the form is submitted.

**Comment by eshtadc** [comment] 2017-05-12 17:44
This appears to be due to how Ember is applying the attributeBindings and a special case for "required".  Looks like the issue is being tracked here: https://github.com/emberjs/ember.js/issues/14737

**Comment by eshtadc** [comment] 2017-05-12 19:10
Additionally this doesn't appear to be related to required="".  You can test this by just rendering `<input type="text" name="testme" required="">` in Firefox and seeing that the validation does not render until there has been a focusout change.

**Comment by martndemus** [comment] 2018-01-11 09:57
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.

**Closed by martndemus** 2018-01-11 09:57 UTC
Labels: bug
